CREATE TABLE VIDEOS 
(
	IDVIDEO VARCHAR(100)NOT NULL,
	TITILE TEXT  NULL,
	POSTER TEXT  NULL,
	VIEWER BIGINT NULL,
	DESCRIPTION TEXT NULL,
	ACTIVE BOOLEAN NULL,
	PRIMARY KEY (IDVIDEO)
);
CREATE TABLE FAVORITES
(
	IDFAVORITE BIGSERIAL NOT NULL,
	USERID VARCHAR(100) NOT NULL,
	IDVIDEO VARCHAR(100)NOT NULL,
	LIKEDATE DATE NULL,
	PRIMARY KEY(IDFAVORITE)	
);
CREATE TABLE USERS
(
	USERID VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(70)NOT NULL,
	EMAIL VARCHAR(255)NULL,
	FULLNAME TEXT NULL,
	ADMIN BOOLEAN NOT NULL,
	PRIMARY KEY (USERID)
);
CREATE TABLE SHARES
(
	IDSHARE BIGSERIAL NOT NULL,
	USERID VARCHAR(100) NOT NULL,
	IDVIDEO VARCHAR(100)NOT NULL,
	EMAIL VARCHAR(255)NOT NULL,
	SHAREDATE DATE NULL,
	PRIMARY KEY(IDSHARE)
)
ALTER TABLE FAVORITES
ADD FOREIGN KEY(USERID) REFERENCES USERS(USERID);
ALTER TABLE FAVORITES
ADD FOREIGN KEY(IDVIDEO) REFERENCES VIDEOS(IDVIDEO);
ALTER TABLE SHARES 
ADD FOREIGN KEY(USERID) REFERENCES USERS(USERID);
ALTER TABLE SHARES 
ADD FOREIGN KEY(IDVIDEO) REFERENCES VIDEOS(IDVIDEO);